export const cardClass = {
  card: [
    "group",
    "w-full",
    "flex",
    "flex-col",
    "justify-between",
    "gap-2",
    "rounded",
    "border",
    "bg-zinc-50",
    "px-3",
    "py-4",
    "text-zinc-700",
    "dark:border-zinc-700",
    "dark:bg-zinc-800",
    "dark:text-zinc-100",
  ],
  cardBody: ["flex", "flex-col"],
  cardTitle: [
    "flex",
    "items-center",
    "gap-1",
    "font-bold",
    "group-hover:underline",
  ],
  cardDescription: ["text-zinc-600", "dark:text-zinc-300"],
  cardTags: ["inline-flex", "gap-1"],
  cardTag: [
    "rounded-full",
    "border",
    "bg-white",
    "px-2",
    "text-sm",
    "dark:border-zinc-700",
    "dark:bg-transparent",
    "dark:text-zinc-300",
  ],
  pubDate: ["text-xs", "dark:text-zinc-300"],
};
